### ISSUE TITLE
Update Changelog

### ISSUE THREAD

**Issue by PowerSchill** [sous-chefs/memcached#101]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

Update all CHANGELOGs to follow standard defined at <https://keepachangelog.com/>

Issue sprouted from sous-chefs/meta/issues/101. If not applicable then issue should be closed.

**Comment by AKovtunov** [comment]
:wave: I hope it matches all your requirements!
Happy hactoberfest :rocket:

**Comment by ramereth** [comment]
@AKovtunov thanks for resolving this!
