### ISSUE TITLE
Multiple Memcached instances using unix sockets

### ISSUE THREAD

**Issue by salsa-dev** [sous-chefs/memcached#83]
There is a need to set up several Memcached instances using unix sockets.

Currently the cookbook supports such a deployment scenario only through setting extra_cli_options ("-a" and "-s" parameters).

It could be useful to support socket configuration resource properties.

**Comment by iennae** [comment]
Thanks for filing this. We are happy to review and pull in a PR if you have an idea around implementation/documentation of this.

**Comment by tas50** [comment]
I’m adding the Type: Jump In GitHub label to this issue. This is a great issue for someone to get their feet wet with and we’d love a PR to resolves the issue.
