### ISSUE TITLE
Update 'user' fails if memcached is already running

### ISSUE THREAD

**Issue by mcoolive** [sous-chefs/memcached#95]
### Cookbook version
version 5.0.1

### Chef-client version
version 12.18.31

### Platform Details
CentOS Linux release 7.3.1611 (Core)
default['memcached']['version'] = '1.4.25-1.el7'

### Scenario:
Upgrade of the cookbook fails when an instance of memcached is already running. It fails on 'user' resource.

### Steps to Reproduce:
- We used a very old version of this recipe based on 52c2c3c.
- An instance of memcached was running
- When we upgrade the recipe, we got an error on 'user' resource:
`Ran ["usermod", "-c", "Memcached", "-s", "/bin/false", "-d", "/nonexistent", "memcached"] returned 8`

### Expected Result:
I expect the user is updated with no restart of memcached (or at least it should be configurable). Maybe we can ignore if some changes are not applied (we don't care of the home directory).

### Actual Result:
In our case, 'memcache' user and group already exist. They were created by the RPM package. Old version of the recipe (before b2e98e6d) do not create/update the user because the group already exist. Recent versions try to update the user (in particular its home dir), but _usermod_ cannot update the home directory when the user is logged (or it is executing memcached).

### Further considerations:
I don't think we should re-configure user or group in our case. But probably other packages do differently... I think we should provide more control on _package recipe. This could solve this issue and allows to customize the installation(for example let us install from a custom tarball).

**Comment by ramereth** [comment]
Resolved in #96
